### ISSUE TITLE
Improve zebra table colors (Network, Storage)

### ISSUE THREAD

**Issue by violasong** [firefox-devtools/ux#10]
These zebra tables look pretty overwhelming. It would be helpful to have subtler background colors based on [Photon Gray](https://design.firefox.com/photon/visuals/color.html#grey) (perhaps Gray-90 at a low opacity?). Currently we don't have sketch files build up Network or Storage, so the easiest way to test the look of new colors may be via [inspecting the toolbox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox). This is needed for both light and dark themes.

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/55994/44434561-bc560e80-a560-11e8-8430-2047b1829c08.png">
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/55994/44434575-c8da6700-a560-11e8-86ce-ea30b04b9fa8.png">

**Comment by fvsch** [comment]
For the light theme:

- The current darker line background uses `--table-zebra-background: rgba(0,0,0,0.05);`, that is black at 5% opacity on top of a white background. It results in a `#f2f2f2` background.
- Photon Grey-10 (with a “e” because Photon is English or possibly Canadian :P) is `#f9f9fa`.

Comparing both:

![devtools-zebra-grey10](https://user-images.githubusercontent.com/243601/44464669-aeb18f00-a61b-11e8-911c-5f4824052924.png)

I kinda feel that Grey-10 is going a bit too far, and would probably shoot for a color in between, maybe `#f5f6f7` (can be achieved with `--table-zebra-background: rgba(20,40,60,0.04);`).

A technical note: a lot of LCD screens tend to “burn” lighter grays, for instance `#f8f8f8` and `#ffffff` can be impossible to tell apart on some screens or monitors. I’m mostly seeing this with cheap LCD screens or badly configured ones. Maybe that’s less of a concern today than it was a few years ago, when my webdesign clients often couldn't see subtle grey backgrounds and separators.

**Comment by violasong** [comment]
One more thought: Maybe the row hover color should look slightly different for each row color. Right now there's a slight weird feeling when hovering because of how the row differentiation goes away.

**Comment by violasong** [comment]
Another example - perf-html uses a slightly lighter gray https://perf-html.io/from-addon/calltree/?globalTrackOrder=0-1-2&localTrackOrderByPid=16148-1-0~16149-0~&thread=2&v=3

**Comment by yogmel** [comment]
Hi!
Can I give this issue a try?
@violasong I couldn't open the link above :( is there any print screen I can use as a reference?
Also, is there any information I should know? I will experiment some color combinations with the Browser Toolbox Inspector and update you here, if that sounds ok.

Thanks!

**Comment by violasong** [comment]
Hi! Ah, looks like that link stopped working - here's what the table looks like:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/55994/46113571-cb555f80-c1a3-11e8-8bca-222dc7aa4ba0.png">

**Comment by fvsch** [comment]
Looks like the gray stripes are `#f5f5f5`. (Maybe achieved with black at 4% opacity: `rgba(0,0,0,0.04)` on white.)

> One more thought: Maybe the row hover color should look slightly different for each row color. Right now there's a slight weird feeling when hovering because of how the row differentiation goes away.

Agreed, that would be ideal. (Another option is to have a hover color that is darker (in the light theme) than the zebra stripes. Part of the confusion is how the light blue used on hover and the light gray for zebra stripes have almost the same luminosity.)

**Comment by yogmel** [comment]
Hi all, so sorry for the delay :(

I have tested on both Network and Storage tabs.

[ORIGINAL - Network]
![01_01](https://user-images.githubusercontent.com/3901809/46958628-a2244280-d070-11e8-9771-af0ac8efccc2.jpg)

[TRY - Network]
![01_02](https://user-images.githubusercontent.com/3901809/46958695-cc760000-d070-11e8-9e68-a6c6033fcb70.jpg)

For this, I have changed the colors of the odd rows and hover:
```css
.request-list-item:not(.selected).odd {
    background-color: #f7f7f8;
}
.request-list-item:not(.selected):hover {
    background-color: #d1e8ff;
}
```

I thought that Firefox's #f9f9fa didn't have enough contrast, although it could be a possibility.
I used @fvsch's advice on setting a darker hover color for the row, to give it more contrast.

With these changes in the style, the storage table was displayed as follows:

[ORIGINAL - Storage]
![02_01](https://user-images.githubusercontent.com/3901809/46958856-24146b80-d071-11e8-9340-82fbf3189f66.jpg)


[TRY - Storage]
![02_02](https://user-images.githubusercontent.com/3901809/46958884-2ecf0080-d071-11e8-91c8-89996ae0af63.jpg)

I'm still struggling with this "Last accessed on" column, but I would like to hear what you have got to say :) Thanks!

**Comment by fvsch** [comment]
This looks great IMO.

The "Last accessed on" column happens to have a `rgba(0,0,0,.1)` background on the column container (it's a XUL table where cells are grouped by column, unlike HTML tables which are grouped by row). So initially we had to RGBA blacks combining, and in your test the odd rows have the `rgba(0,0,0,.1)` background and the even rows have your lighter opaque zebra color.

We have 2 options:
1. Fix the "Last accessed on" column style in CSS
2. Maybe remove that column style altogether or find an alternative? This style is meant to show that this column contains values that can't be edited. Other values can be edited by double-clicking them first. But frankly I'm not sure that style manages to communicate this meaning, so maybe we should just remove it.

**Comment by janodvarko** [comment]
I like the new zebra color on the Network monitor!
Happy to R+ working patch for it.

Thanks for helping with this!
Honza

**Comment by yogmel** [comment]
Hi all,

@fvsch thanks for the info! I managed to change the colors. I have changed the opacity, so it doesn't look so contrasting, but people can still tell there's a difference (maybe?).

[1st TRY - Storage]
![02_02](https://user-images.githubusercontent.com/3901809/47086362-a2971780-d1ef-11e8-9c56-ca4bf00832fb.jpg)


[2nd TRY - Storage]
![02_03](https://user-images.githubusercontent.com/3901809/47086941-2c93b000-d1f1-11e8-8154-612a8c2c03f3.jpg)


--

I tried to set the whole column with one single color, but I don't think it's going to be readable for each row :|
![02_04](https://user-images.githubusercontent.com/3901809/47087006-4e8d3280-d1f1-11e8-993b-3d4768ed4646.jpg)




@janodvarko thanks :') happy to be able to help
I'm sorry for the ignorance, but what would be "R+"?

**Comment by janodvarko** [comment]
> @janodvarko thanks :') happy to be able to help
> I'm sorry for the ignorance, but what would be "R+"?
Ah, this has been forgotten!

Please file a bug in Bugzilla, using this link:
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Netmonitor

Attach a patch to the bug and ask me for review.

Thanks!
Honza

**Comment by violasong** [comment]
Hi @yogmel! Sorry from the delay in responding to this, but I love the 2nd try - I think it would look even better if the alternate "Last Accessed on" background colors were switched.

**Comment by yogmel** [comment]
Hi @janodvarko I have created the issue in this link: https://bugzilla.mozilla.org/show_bug.cgi?id=1508241
I will check how I create a patch and if I have any questions I'll ask them here.

Hi @violasong I will change the colors and post it again here as soon as it's done.

**Comment by yogmel** [comment]
Hi @violasong, just a heads-up that I've worked with Honza and the Zebra colors for the Network tab was already sent as a patch.

If you need further assistance for the Storage table, please let me know.

**Comment by violasong** [comment]
Wonderful to hear this - thanks @yogmel!
