### ISSUE TITLE
@nchevobbe visual summary of the options you proposed:

### ISSUE THREAD

**Issue by brakcoinnn** [firefox-devtools/ux#107]
@nchevobbe visual summary of the options you proposed:

OPTION 1: `+` button

<img src="https://user-images.githubusercontent.com/2797254/72428367-cef06980-378d-11ea-8797-17b93f9b599e.png" width="320" />

OPTION 2: `Add property` button

<img src="https://user-images.githubusercontent.com/2797254/72428495-1bd44000-378e-11ea-851b-20b7f1fe40ad.png" width="320" />

both can be enabled just on :hover as you wrote. Did I understand it right?

Another option I was thinking of is to do it the same as "Watch expressions" or "XHR Breakpoints" panes, where there's just text (a placeholder into a input with no outline)

<img src="https://user-images.githubusercontent.com/2797254/72428706-89806c00-378e-11ea-991a-36b6f862abe3.png" width="320" />

_The above sketches were done just to investigate the options visually, no focus on style (if needed I can redo them with the right style, if I have access to the Dev Tools style guide)_

_Originally posted by @luc4leone in https://github.com/firefox-devtools/ux/issues/106#issuecomment-574611538_

**Comment by fvsch** [comment]
@brakcoinnn It looks like you opened a new issue with the content of a comment from an existing issue, but I'm not sure if you wanted to explore a different topic. Should we close this issue?

**Comment by brakcoinnn** [comment]
💯💯💯💯💯💯

**Comment by brakcoinnn** [comment]
https://user-images.githubusercontent.com/2797254/72428706-89806c00-378e-11ea-991a-36b6f862abe3.png
