### ISSUE TITLE
Clear Console Icon at the "seperated console" bar!

### ISSUE THREAD

**Issue by BerkerYuceer** [firefox-devtools/ux#110]
We already got a clear console icon in the console page but what I am actually requesting is to have another clear console button at the "Seperated Console" section!

Chrome has that so Firefox Developer Edition should have a better version of it. It will just clear the console log. This way "log loop" caused issues also can be solved by devs without breaking the firefox window.

![console clear](https://user-images.githubusercontent.com/2599466/74347384-12a4b600-4dc2-11ea-8b7f-8d464f3e3757.png)

This little detail would help immensely.

**Comment by fvsch** [comment]
Hi @BerkerYuceer. We already have a clear button in the Console tab and in the split Console (the one shown in your screenshot).

I think what's happening in your screenshot is that there was a CSS bug where the split console's toolbar was missing some buttons and had misplaced buttons. This is fixed on Nightly.

@nchevobbe Do you know if this bug impacted Release/DevEdition and if we're backporting a fix?

**Comment by BerkerYuceer** [comment]
By the way I am using Firefox Developer Edition 74.0b1 (64 bit)

**Comment by nchevobbe** [comment]
yes, that's https://bugzilla.mozilla.org/show_bug.cgi?id=1613668 , and it will be uplifted to beta.

**Comment by fvsch** [comment]
Good to know. @BerkerYuceer You should get the fix in a few days, but in the meantime you can use the keyboard shortcut to clear the Console:

- Windows and Linux: `Ctrl + Shift + L`
- macOS: `Ctrl + L` or `Cmd + K`

https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts#Web_Console

**Comment by BerkerYuceer** [comment]
@fvsch & @nchevobbe thanks for the keyboard shortcut, waiting for fix.

**Comment by nchevobbe** [comment]
@BerkerYuceer it should be on 74.0b3 if you update
