### ISSUE TITLE
Combined Initiator/Cause column

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/ux#117]
Follow up from https://github.com/firefox-devtools/ux/issues/87#issuecomment-517502725 and [bug 1592535#c2](https://bugzilla.mozilla.org/show_bug.cgi?id=1592535#c2).

cc @bomsy @Transfusion @janodvarko @fvsch 

Assumptions:

- Chrome doesn't have _Cause_ but has _Type_  and _Initiator_
- _Cause_ is often redundant with _Type_ (which also has more detail)

**Example requests:**

<img width="376" alt="image" src="https://user-images.githubusercontent.com/8599/75291331-d8321480-57d6-11ea-893b-f419949079ff.png">

_Github_ (Interesting to note here is that the images should also have stacks, but [CSS stacks are not supported](https://bugzilla.mozilla.org/show_bug.cgi?id=1300979) atm)

<img width="374" alt="image" src="https://user-images.githubusercontent.com/8599/75291429-0879b300-57d7-11ea-8cd9-44c50e3ab3cd.png">

_Airtable XHR requests_

Proposed information hierarchy would be 1st _Initiator stack_ and 2nd _Cause_, which leads to the following formatting:

- Without stack: `cause`
- With stack: `location.js:line:column (cause)`

This already expects that `(cause)` and longer locations will overflow on small spaces; which should be OK as the initial filename + tooltip should still be enough to orient yourself.

## Decision

Accepted the proposed `cause`/`location.js:line:column (cause)` format.

**Comment by violasong** [comment]
Closing as completed
