### ISSUE TITLE
Inline error annotations in Debugger

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/ux#124]
https://phabricator.services.mozilla.com/D71337 is adding inline error annotations.

If an error is thrown the line gets annotated with an error icon that shows the error message + stack on hover.

The same mechanism could eventually also map console error and warnings to console locations to show them in context when loading a source and stepping through the code.

The idea would be to unblock landing the work soon and to file follow up bugs for UI polish.

@jasonLaster brought up a point, that the expression could be red underlined without an icon. Maybe the styling could be similar to matched strings, but in red?

<img width="79" alt="image" src="https://user-images.githubusercontent.com/8599/80561046-fe6f5e80-8997-11ea-89b9-22a19dc554f2.png">

**Comment by digitarald** [comment]
The latest design from the patch switched to curly underline: 
![image](https://user-images.githubusercontent.com/8599/80644460-87c97400-8a1e-11ea-99f8-64e9f09d9956.png)

**Comment by jasonLaster** [comment]
Yep, I think microsoft word taught us that this is what errors look like and other products like vs code have reinforced it. I'd be fine removing the red line background as that might be a bit noisy for a feature that is just a bit of additional information.

**Comment by violasong** [comment]
Cool, looking good!

I see the curliness matches VSCode but it seems a bit more dramatic than it needs to be - I can experiment with a more minimal look. 

The red background was making me think these were errors that would keep the app from running - if they're not that major then removing it makes sense.

Comparisons: 

VSCode
<img width="134" alt="image" src="https://user-images.githubusercontent.com/55994/80651509-e399fa00-8a2a-11ea-86a0-8a1f45d41f2b.png">

Xcode 
<img width="198" alt="image" src="https://user-images.githubusercontent.com/55994/80651377-b1889800-8a2a-11ea-95f0-1eaece381c1b.png">

goog docs
<img width="93" alt="image" src="https://user-images.githubusercontent.com/55994/80651257-72f2dd80-8a2a-11ea-8f4b-5638fe371e8f.png">

**Comment by jasonLaster** [comment]
Thanks for the comparables. 

These exceptions do stop the program at these points. Some examples of this are `foo.doSomething` where foo doesn't exist or `doSomething` is not real... In these cases the programs throw an exception and bail out.

**Comment by Anurin1** [comment]
I am just wondering if the underline without the line background doesn't get lost in more 'dense' sources?
![line-background](https://user-images.githubusercontent.com/48520954/80686974-dd0e8f80-8ac9-11ea-9bdf-8c137a7675db.png)

Btw. we could also discuss the styles of the tooltip? Now it copies styles from the console. What do you think?
![tooltip](https://user-images.githubusercontent.com/48520954/80687418-8ce3fd00-8aca-11ea-9b2f-a9b54ad4ae28.png)

Also, do you think when hovering over the underlined token the background should change? In pause state, there is this yellow background while hovering, not sure if it's needed here.
![tokenHover](https://user-images.githubusercontent.com/48520954/80687547-be5cc880-8aca-11ea-9ec6-20bb53348a9b.png)

**Comment by violasong** [comment]
Ah, line background seems good to me. Looks like it might be a slightly different color than the Console error background at the moment - would be great to match it.

The tooltip with red styling looks a bit odd when juxtaposed with the other red row. I'd suggest the regular styling for that.

It would be good to give the token a hover background. We can use that same yellow for now,  though it should probably be revisited separately (should probably be a blue instead).

**Comment by Anurin1** [comment]
Thanks Victoria!

I'll match the exception background color with the console error background color and keep the yellow background color on hover for now.

> The tooltip with red styling looks a bit odd when juxtaposed with the other red row. I'd suggest the regular styling for that.

What did you mean by regular styling for the tooltip? Something like this?
![exc-tooltip](https://user-images.githubusercontent.com/48520954/81077208-f90c9980-8eec-11ea-9dfd-f7398ba1ee6c.png)
Should the text color be changed? Now it's the same as the console text error color. Thank you.

**Comment by violasong** [comment]
This looks good! I had been thinking of making the tooltip black on white, but I think using the red text color helps relate it to the error row.

**Comment by violasong** [comment]
Looks like the [associated bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1581708) is fixed? Closing unless we need a new polish bug.
