### ISSUE TITLE
Error in Design with the Bookmarks Tab

### ISSUE THREAD

**Issue by anshdhinhgra47** [firefox-devtools/ux#132]
**Purpose:** 
This issue shall discuss the current design of the bookmarks tab. The following is the image of the bookmarks tab as it appears on my screen whenever I open the Firefox Browser.

**Suggestion:**
I was thinking if instead of an arrow and a separate folder, we can only have an arrow for accessing other bookmarks, pinned on the bookmarks bar. The two of them do not look good  together.

**System Specifications:** macOS Big Sur, Version 11.1, MacBook Pro (13-inch, 2020)
**Current Firefox Browser Version:** 84.0.2 (64-bit)

**Imag Reference:** 
<img width="217" alt="Screenshot 2021-01-23 at 10 20 27 PM" src="https://user-images.githubusercontent.com/56676059/105608577-bddb2f00-5dc9-11eb-97b0-0837c317cc9f.png">

**Comment by violasong** [comment]
Hi! This github project is actually just for Firefox DevTools, not the main Firefox, so I'll close it. Further questions can be sent to https://support.mozilla.org/en-US/.

Something that might help: you can right click Other Bookmarks and select "Hide Other Bookmarks." After that, you can still add a folder to your bookmarks toolbar that would end up in the >> if it's too long.
