### ISSUE TITLE
Inconsistent accordion hover colors

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/ux#24]
Accordion headers (for example the “▶︎ Grid” and “▶︎ Box Model” headers in Inspector>Layout) have different background colors on hover.

In the dark theme, I’m seeing at least 3 colors:

1. Inspector>Rules, Debugger: blueish gray
2. Inspector>Layout, Inspector>Fonts: slightly lighter gray
3. Network details: lighter gray (and missing on the first accordion header in "Headers").

There are 3 different colors in the light theme too.

We also have inconsistent cursors on hover: `default` (arrow) or `pointer` (hand).

**Comment by aburone** [comment]
Network
In response headers and request headers there's more inconsistencies. Seems like the styles are changed with js.
Go over one header and you have a background-color. Click and the background-color is gone.
Go over the other header and click it. Now the first header has his background again
---
What should be the background-colors on hover for all those headers?
Looks like the ideal situation to use a css variable

--header-back-color
--header-back-color-hover ?

**Comment by janodvarko** [comment]
I think that we should use the same styiling & design as the Fonts side-panel in the Inspector panel.
And if there are css variables we can use - even better.

> --header-back-color
> --header-back-color-hover ?

I am unsure about what var is the right one. I am also seeing:

--accordion-header-background

@mcroud Any pointers what CSS var to use for headers in side panels?

Honza

**Comment by mcroud** [comment]
There's a lot of variation here! I've taken to making a bit of a visual audit. 

![toolbar-audit](https://user-images.githubusercontent.com/42435754/47438214-eff02780-d7a1-11e8-86d7-21bac8f9f66e.png)

[Toolbar header hover audit](https://mozilla.invisionapp.com/share/W4OR7SIJ6HP#/327459059_Toolbar_Header_Audit)

The Fonts panels "All font on page" header is the most compliant in light mode using `--theme-toolbar-hover`, however in dark mode it is extremely subtle and doesn't translate to a Photon color. I've not delved deep into the variable usage (where else it's used?) but if we can get --theme-toolbar-hover in dark mode to use something like grey-80 I think that could be the standard to go by.

W3C stipulates that a [pointer cursor](https://www.w3.org/TR/css-ui-3/#valdef-cursor-pointer) should only be used for links (though I can understand that as a more muted control it may be in effect to highlight it is interactive beyond a color change). We use the default cursor for buttons, tabs and menu items so there is a legitimate question to ask if it has a place in panel headers.

**Comment by fvsch** [comment]
Using Grey 20 / Grey 80 looks like a good option.

It seems we often use `cursor:pointer` for some elements which have no :hover styles or for small icons (e.g. some icons in the Inspector), but it looks like it's the exception more than the rule. So I would remove `cursor:pointer` (using `cursor:default` instead) for non-links, as long as we provide a not-too-subtle hover effect.

**Comment by fvsch** [comment]
The cursor thing is a good example of something which could be discussed and codified in a UX style guide, so we can make consistent improvements over time.

**Comment by mcroud** [comment]
> The cursor thing is a good example of something which could be discussed and codified in a UX style guide, so we can make consistent improvements over time.

Totally agree!

**Comment by fvsch** [comment]
Fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1525939
