### ISSUE TITLE
RDM toolbar icons

### ISSUE THREAD

**Issue by violasong** [firefox-devtools/ux#28]
(assigned to Yash)

This is a bug to track work on the toolbar icons, including rotate, touch, and screenshot.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/55994/45109473-83876f00-b0f4-11e8-83d4-52b490382cb7.png">

**Comment by violasong** [comment]
Latest variants from Yash:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/55994/45116988-3bbf1280-b109-11e8-9006-db46c0d61dd6.png">

**Comment by violasong** [comment]
The rotate icon is awesome!

The touch icon is getting really close — I think it's still just a tiny bit too abstract in style and could use some photon-ization. Ideas: 
- Fill in the hand so that it's dark
- Adding 3 little bumps for the folded fingers, giving a bit more separation for the thumb, and slight rounded corners for the "wrist" could help make it look a bit more clearly hand-like
- Maybe the semi-circle for touch could actually be a line or a less rounded curve? (to keep the perspective a bit more head-on)

**Comment by yashjohar** [comment]
Thanks Victoria! Those are some really good ideas. I'll see if the hand can be made a little less abstract.

**Comment by yashjohar** [comment]
The new hand icon:
![rmd-toolbar-icons](https://user-images.githubusercontent.com/8113279/45250458-37853600-b351-11e8-8a18-3a678da1b18b.png)
Let me know what you think. Thanks!

**Comment by violasong** [comment]
Hi Yash! So sorry for the delay. I really like the changes you made - I just have a few more suggestions if you don't mind. I quickly drew over your latest version in photoshop to show the ideas - wider at top of fist and narrower at the bottom, rounder and taller fist, and more finger definition.

small:
<img width="46" alt="image" src="https://user-images.githubusercontent.com/55994/45581887-51e07780-b85b-11e8-8149-bfe049bcb5c8.png">
large:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/55994/45581891-586eef00-b85b-11e8-9d2b-968bb185e6c4.png">

I also tried filling it in for photon but it seemed a lot less clear. I think sticking with the lighter version is fine for this secondary style of toolbar.

<img width="39" alt="image" src="https://user-images.githubusercontent.com/55994/45581926-0c707a00-b85c-11e8-8b10-ee571868455d.png">

**Comment by fvsch** [comment]
@yashjohar Do you happen to have your icons in SVG?

For screenshots, [bug 1517189](https://bugzilla.mozilla.org/show_bug.cgi?id=1517189) implements a new camera icon (see #36), so we should probably just use that.

**Comment by yashjohar** [comment]
Thanks @violasong . Is there a bug for implementation?

**Comment by violasong** [comment]
Hey Yash! Looks like it would be best to make a new bug for both this and the rotate icon.

**Comment by fvsch** [comment]
@yashjohar I opened [bug 1535254](https://bugzilla.mozilla.org/show_bug.cgi?id=1535254) on Bugzilla. Do you have an account there, so that I can assign you to the issue? Or do you need help with the implementation?

**Comment by yashjohar** [comment]
@violasong I have a Bugzilla account <yash.johar1992@gmail.com>. You can assign the bug to me. Thanks!

**Comment by yashjohar** [comment]
Hi @violasong @fvsch sorry for the delay. I have attached the rotate and touch icons to the [bug 1535254](https://bugzilla.mozilla.org/show_bug.cgi?id=1535254). I don't have a copy of Illustrator and will need some help optimising them.

**Comment by violasong** [comment]
No worries and thanks @yashjohar! Excited to see these land.
