### ISSUE TITLE
Redesign Reader View settings panels with Photon Styling

### ISSUE THREAD

**Issue by violasong** [firefox-devtools/ux#5]
Note: This isn't actually DevTools, but is a great issue to work on for anyone who wants to help polish Firefox's accessible reading experience! This is for Desktop Firefox, but any improvements made here could be adapted for Firefox mobile.

## Research
1. Go to a page that supports reader mode, like this [NYTimes article](https://www.nytimes.com/2018/08/14/opinion/how-to-cut-greenhouse-gas-emissions-without-taxing-them.html).
2. Click on the Reader View icon <img width="28" alt="image" src="https://user-images.githubusercontent.com/55994/44357019-d9f27d80-a465-11e8-9575-7cc5b85a91ec.png">
3. Take a look at the type controls panel:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/55994/44357055-f7274c00-a465-11e8-9ba1-9b00888baab1.png">
and also the narration controls panel:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/55994/44357084-073f2b80-a466-11e8-8376-0dcfa17224f5.png">
Including the narration panel's voice options:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/55994/44357169-2ccc3500-a466-11e8-87f2-2363a38e5561.png">

## Tasks
- Task 1: Propose mockups for these panels that better align with the [Photon Design System](https://design.firefox.com/photon/welcome.html).

- Task 2: Using the [icon instructions](https://design.firefox.com/photon/visuals/iconography.html) and existing [Photon icons](https://design.firefox.com/icons/viewer/) as a guide, design new icons where needed. There's a new turtle icon in the tracking protection UI that we could use: [Slow.svg.zip](https://github.com/devtools-html/ux/files/2320037/Slow.svg.zip)

- Task 3: Suggest improvements to the Reader View main UI.

- Task 4: For the Dark and Sepia themes, choose new matching colors for the panels and main left-toolbar UI.

- Implementation: Once the design is complete, either the designer(s) assigned or another contributor can work on front-end implementation of the design. A Firefox engineer will be available to help. 

- Optional: If you're using Sketch, you can [download the mockup](https://drive.google.com/file/d/1JvGya_Vn9Phndwc2RkB5vBuzAvFxPenq/view?usp=sharing) for the current design.

### URL bar dropdown
<img width="710" alt="image" src="https://user-images.githubusercontent.com/55994/44357298-816fb000-a466-11e8-84b2-4d185b207eca.png">

###  This doorhanger
<img width="306" alt="image" src="https://user-images.githubusercontent.com/55994/44357360-acf29a80-a466-11e8-9176-33802342a25e.png">

###  Firefox tabs
<img width="507" alt="image" src="https://user-images.githubusercontent.com/55994/44357475-fe028e80-a466-11e8-87f6-792029df1e7b.png">

### Preferences tabs
<img width="214" alt="image" src="https://user-images.githubusercontent.com/55994/44359797-c0553400-a46d-11e8-8e30-1197cbeaa5ef.png">

**Comment by violasong** [comment]
@caterinasworld will be starting on tasks 1, 2, and 4. We're looking for one or two more designers to work with her on task 1 or claim task 3.

**Comment by bryanbell** [comment]
One of the main issues with the reader mode is that it relies on a sidebar toolbar, which is easily missed by users as they scan down the page visually.  Longtime Reader Mode Users have been known to overlook the Save to Pocket and Narrate options. 

Moving these to the top of the screen and inline with the content of the page would go a long way to drawing attention to these handy features. 

Abe has down some UX work on this option already:  https://mozilla.invisionapp.com/share/87N9YQYCTJZ#/screens

**Comment by violasong** [comment]
Hi @caterinasworld and @Gabiskandar! Just wanted to check if you want to keep working on this - I would also love to see anything you might already have done :).

We now have an internal person who can take this on, so no worries at all if you need to pass on this. Thanks!

**Comment by berkaybarlas** [comment]
Hello @violasong and @caterinasworld

I'm a third year Computer Engineering student in Koc University. I have experience with Java, C++ and Javascript languages and UI/UX design. I have gone through the ideas and I would love to work on Firefox Reader. 

I thought that I could start with trying solve this issue. Is there anyone currently working on this issue?
Thanks!

**Comment by violasong** [comment]
Hi @berkaybarlas! I'll check with the other Mozilla designer who was working on this and get back to you :)

**Comment by blenderskool** [comment]
Hi @violasong 

I would be glad to work on this project either on UI mockups or the frontend implementation along with @berkaybarlas if possible.
I went through the GSOC 19 ideas and this is something that excites me 😄 
Thanks

**Comment by violasong** [comment]
Hi @blenderskool! For this bug, let's wait for @awallin to get back to us for next steps, since he's the main designer on this project.

**Comment by ruchikabgosain** [comment]
Hello @violasong is this issue still available? I would like to take this up. Let me know! :)

**Comment by awallin** [comment]
Hi @ruchikabgosain thanks for your interest in this issue. It's actually being worked on this summer by another contributor as part of the Google Summer of Code.

**Comment by violasong** [comment]
I'll close this bug, but we can file new ones if more work on this is needed after the summer. Thanks all!
