### ISSUE TITLE
Align Inspector toolbar height with other panels

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/ux#52]
The Inspector's top toolbar is currently 23px tall (excluding borders). We have [a bug on file for making it 24px tall](https://bugzilla.mozilla.org/show_bug.cgi?id=1512513) with a patch, but I'm wondering if we should just align it with Console, Network, Debugger, Accessibility and use a 28px height instead?

With the bigger and fatter Photon icons, 24px can look a bit cramped, and it could be nice to be consistent here.

Accordion headers and the breadcrumbs could remain 24px.

Here's what a quick test looks like (please disregard the breadcrumbs):

![inspector-toolbar-28px](https://user-images.githubusercontent.com/243601/53940388-e236a100-40b5-11e9-97ea-1ab38feb0074.png)

Pinging @violasong @captainbrosset @gabrielluong.

**Comment by captainbrosset** [comment]
I like it. Consistency is the most important.

**Comment by violasong** [comment]
Interesting, thanks for bringing this up! I think this will make a lot of sense, especially since we are planning to do more with that markup view toolbar, with filter badges similar to Console/Network.

**Comment by oslego** [comment]
Agreed. It looks more elegant, especially with the redesigned search/filter input fields.

**Comment by fvsch** [comment]
I'm working on it in [bug 1535956](https://bugzilla.mozilla.org/show_bug.cgi?id=1535956).

**Comment by fvsch** [comment]
Closing this since we have a UX decision already, and work underway.
