### ISSUE TITLE
Provide option to enable (expensive) variable mapping

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/ux#53]
UX for https://github.com/firefox-devtools/debugger/issues/7806 by @jasonLaster 

Assumptions:
- Default off, because of performance overhead
- Only possible to enable for files with column-based source maps
- MDN link to learn more

Ideas

![image](https://user-images.githubusercontent.com/8599/54056656-98c57f00-41a5-11e9-8550-80aecf9ac628.png)

1. Panel header checkbox, inspired by Chrome `async` option
2. In-panel checkbox
3. Panel header options dropdown
4. (not done) Link in panel that onboards users into the options menu

**Comment by jasonLaster** [comment]
Here are some updates based on my interpretation of our discussions.

CC @digitarald 

![image](https://user-images.githubusercontent.com/254562/54454886-e0618300-4730-11e9-8e6a-89c7f904d86a.png)

**Comment by digitarald** [comment]
Ok, let's go with this, @jasonLaster . I assume the gray box in the screen on the top right is the tooltip?

**Comment by digitarald** [comment]
@jasonLaster can you confirm that the initial UX decision is to use the checkbox + `Map` label in the panel-header (and removing the link to show generated scope)?

**Comment by digitarald** [comment]
Landing in [bug 1536216](https://bugzilla.mozilla.org/show_bug.cgi?id=1536216).

**Comment by violasong** [comment]
Looks like this was resolved (and it looks good to me!), so closing this bug.
