### ISSUE TITLE
[Console] Editor Onboarding

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/ux#85]
(_Edited by digitarald_)

This onboarding should probably split into 2 separate designs, that can be discussed together here for the sake of a holistic end to end experience.

1. In-context editor hint for awareness, tell users that they could switch to editor for a better multiline editing experience:

  1. Onboarding should be contextual and only trigger when users paste (or type) snippets with multiple lines into the input.
  2. Onboarding must not steal focus or hide big parts of the UI
  3. Showing onboarding should not change the layout drastically, moving critical elements around

Constrains for feature onboarding:

- Implementation tracked in [Bug 1558417](https://bugzilla.mozilla.org/show_bug.cgi?id=1558417)
- [Requirements document](https://docs.google.com/document/d/18E5QvlKd6vxupq-hVFMtDaNS43zSREWyiZjQ1qjdeFw/edit#)
- [Initial mockups](https://mozilla.invisionapp.com/share/6XQ1CM58JQB#/screens/345519928)

Should highlight a few editor differences from the inline input, in context of user benefits

Kicking off brainstorming: "Editor mode gives you more space to write code snippets and run them repeatedly (`Ctrl+Enter`)"

---

The Editor mode is almost complete \o/
(We're missing a proper way of opening it, and probably a UI review on the Editor toolbar)

What I wanted to discuss here is if we should have something to guide users through this new feature, and the differences with the in-line input.

My reasoning is that users might be confused when switching to editor mode for the first time?
The editor can be enabled with a keyboard shortcut, so some users might enable it without wanting it and find it weird. So maybe that could be mitigated with a piece of UI that says "hey, that's the new editor feature, you can use <kbd>Enter</kbd> as you want, <kbd>Ctrl+Enter</kbd> evaluates the input and *does not* clear it"

What do you think folks?

**Comment by fvsch** [comment]
Sounds like a good idea. I can see users being confused if they triggered the Editor mode by mistake or out of idle curiosity. And even if they wanted the Editor in the first place, spelling out how the keyboard shortcuts work would help!

I can probably make a mockup in a couple days.

Do we also have shortcuts for the history navigation?

**Comment by nchevobbe** [comment]
Thanks a lot @fvsch !

> Do we also have shortcuts for the history navigation?

Not yet. I think it would be nice to have some, but it's also tricky to pick good ones

**Comment by digitarald** [comment]
@violasong maybe a good MVP for pointing the feature out is the fox-themed tooltip we used previously. What are your thoughts?

**Comment by SebastianZ** [comment]
The user should definitely get a hint after switching to the editor mode. A tooltip might help, not sure how the "fox-themed" would look like. I just want note that the text might get a little longer when there should also be the info on how to get back to single-line mode.

Sebastian

**Comment by SebastianZ** [comment]
If the line gets too long, maybe just link to an MDN page for further information on how to use the Editor Mode. The message would then look something like this:

"Editor Mode enabled, press [ |-] to return to Single-line Mode. Learn more"

Sebastian

**Comment by violasong** [comment]
Here's the fox recommender we've used before :D

<img width="343" alt="image" src="https://user-images.githubusercontent.com/55994/62744539-d13ee280-b9fb-11e9-85f7-68e4b163bc63.png">

The tooltip style would be for calling out the editor button, but that would probably be tricky with that button moving unpredictably as more logs come in. An alternative for calling out the editor button would be using a blue "New" dot indicator.

If we want a message within the editor itself, we can use an inline banner style, which we've used for Grid Inspector.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/55994/62744610-2c70d500-b9fc-11e9-9674-48dcdf35bc76.png">

**Comment by digitarald** [comment]
Maybe this can spawn some mockups or further ideas:

**Editor feature hint**: Nicolas had a good idea to just animate the icon when the user starts writing multiple lines (or pasts in a longer snippet). A quick "jump" with fade to blue might be enough to get the users attention.

**Onboarding**: The _inline banner style_ is probably best for this sidebar-styled. Positioning it below the toolbar would bring it in the right context.

Word-smithing drafts:

- _"Editor mode lets you iterate and execute longer snippets"_
- _"Iterating faster on code in the new multiline editor mode. Use `Enter` just like in your normal editor to add new lines and execute with `Cmd-Enter`"_
- "New: Use multiline editor mode for authoring script snippets. | [use of shortcuts]"

**Comment by digitarald** [comment]
@nchevobbe just wanted to check if I captured your idea correctly and if you got anything to add?

**Comment by nchevobbe** [comment]
no, it does look great 👍.
I'll file separate bugs for those 2 things

**Comment by nchevobbe** [comment]
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/578107/63348762-40043000-c35a-11e9-9777-ec46d9e569ce.png">

@violasong , is the background color in a variable somewhere? If not, what should we use in dark mode? Thanks!

**Comment by violasong** [comment]
- Very nice! We can use the Inspector's row hover-background color
- San-serif font would be good
- Fox icon needs more left/right margin. Blue area could use a bit less top/bottom padding (e.g. bottom close button should match the higher close button's spacing)
- The double close buttons are a bit unfortunate. We could instead have a right-aligned link under the text that says "Got it!" (I feel we have a pattern like this somewhere?... But if we just want to land this, the double buttons are fine for now)

Suggestion for the copy:

Iterate on your code faster with the new multiline editor mode. Use **Enter** to add new lines and execute with **Cmd-Enter**.

The run button looks a tiny bit confusing (ok, this is starting to go off into general polish) - one thing we could try is add a "play" icon (from netmonitor) to the button. 

It also needs a bit less top/bottom padding (can match console clear button's hit area) and a bit more left/right padding. Also more left margin. Sorry if this is confusing :). Basically I think it doesn't need to line up with the picker icon - it would be easier to understand if it popped out a little more.

**Comment by violasong** [comment]
(Also, I can actually do a figma mockup if that would help :))

**Comment by fvsch** [comment]
Nit: since the message has 2 sentences, I feel that both should end with a period.

> The run button looks a tiny bit confusing (ok, this is starting to go off into general polish) - one thing we could try is add a "play" icon (from netmonitor) to the button.

Agreed, I think Nicolas said the Editor mode's toolbar needs a UI review and polish pass.
Maybe a good case for making progress on #89 too?

**Comment by nchevobbe** [comment]
> (Also, I can actually do a figma mockup if that would help :))

A mockup would be great :)

**Comment by nchevobbe** [comment]
I tweaked the padding and margin, and added the netmonitor play button before the "Run" text.

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/578107/63575073-7a074900-c589-11e9-9c3d-7c7f468cfea4.png">

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/578107/63575087-85f30b00-c589-11e9-8025-2c042340ce9e.png">

---

The icon feels a bit weird to me in regards to other icon. I guess we should have a stroke-only shape, like the debugger "Resume" button?

Small question: the `Got it!` element is a button that I styled as a link.
1. Is this the look we want?
2. Should I also put `cursor: pointer;` ?

**Comment by fvsch** [comment]
> I guess we should have a stroke-only shape, like the debugger "Resume" button?

We're planning to change the debugger's Resume icon, and unify all the "Play" icons (in Inspector>Animations, here maybe, in Netmonitor and Debugger). Not sure if we're going with a 2px stroke and no fill or some other style.

**Comment by fvsch** [comment]
> I noticed that the history and close button hover states are still taller; I guess they should also be aligned?

This ties in nicely with the questions in #89. :)

I think the 20px height may be a tad short for icon buttons. We use 16px icons and the buttons tend to have a 26px width, so 26x20 can look a bit pill-shaped.

In our older 24px toolbars, those icon buttons are 26x22. In the newer 28px toolbars, button height is all over the place (20px, 26px…), depending on what we did with Flexbox (stretch or center).

**Comment by nchevobbe** [comment]
Some screenshots: 

<img width="756" alt="image" src="https://user-images.githubusercontent.com/578107/63753859-3035a000-c8b4-11e9-8499-88eb66400ae6.png">

For the Run button, I wonder if it would e more pleasing to the eye to line up the icons left borders:

<img width="130" alt="image" src="https://user-images.githubusercontent.com/578107/63754001-6bd06a00-c8b4-11e9-8ad1-ae611acc6714.png">

<img width="212" alt="image" src="https://user-images.githubusercontent.com/578107/63754045-7b4fb300-c8b4-11e9-885e-1568c6bc1bf2.png">

Also, should we go with a thicker style for the Run button to better match the style of the node picker?

**Comment by fvsch** [comment]
> Also, should we go with a thicker style for the Run button to better match the style of the node picker?

Yep, but we can land it in a second step. This is covered by #49 I believe. Jason was looking into this issue these days because he's doing some polish work on Web Replay.

**Comment by nchevobbe** [comment]
Thanks a lot @violasong and @fvsch ! I proceed with the current design and the patch is now in review.
