### ISSUE TITLE
[Debugger] Inline variable preview

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/ux#86]
Debugging UIs are complex, so showing more context within code allows users can focus on just their code source and how it executes. Inline preview shows local values in context, with the code, while users pause and step; so it is easier to see state and changes.

Leads: @dhyey35 @darkwing 
Supporting: @loganfsmyth @janodvarko @jasonLaster 

Related:
- [Requirements document](https://docs.google.com/document/d/1_vCOdOmrGyHWXThds5F6ZkSfvoeIamQnwM4B8FAYZvg/edit#heading=h.15vj0jcl6uv)
  - [Related work](https://docs.google.com/document/d/1_vCOdOmrGyHWXThds5F6ZkSfvoeIamQnwM4B8FAYZvg/edit#heading=h.15vj0jcl6uv)
  - [Jason's mockups](https://www.figma.com/file/UgGU4s3nqL1vXILvhNEuexsQ/Preview)

Technical constraints:
- The information the preview has is the variable _name_ (or _property path_) and the _value_
- Value preview is done using devtools reps
  - Gives us a rich, highlighted preview
  - Could even be interactive
- Small horizontal viewports and code with long lines could lead to previews causing scrolling, and being outside the default viewport
- Diverging: Variables can be interactive, one could imagine shortcuts for creating watchpoints or watchpoints (pause on variable access)
- _Please add more, I will add them as comments come in_

Example of current state of work, showing variables and property values:

![image](https://user-images.githubusercontent.com/8599/62169630-917e4980-b2dd-11e9-80b1-4886935bb6b6.png)

**Comment by digitarald** [comment]
I like Jason's exploration where the value and variable are nicely separated with [subtle boxes](https://www.figma.com/file/UgGU4s3nqL1vXILvhNEuexsQ/Preview?node-id=3%3A74) . [Here my take](https://www.figma.com/file/U5elF7e4V3JM5uuJyYqwfA/Inline-Variable-Preview?node-id=0%3A1) on it, highlighting the variable name and only outlining the value.

**Comment by jasonLaster** [comment]
That looks good.

I'd like to also explore the different interactions as well. 

- expanding/collapsing
- previewing
- context menu options like
  - copy to clipboard
  - copying the variable to the console 🏅

**Comment by fvsch** [comment]
Some accessibility questions:

- How should it read in a screen reader? Should there be a visually hidden label to make sure the code and previews are separated? Without intervention, this content might be hard to understand without information from layout and visual helpers:

> var x = { a: 2, b: 'o' } x { a: 2, b: "o" }

Maybe something like:

> var x = { a: 2, b: 'o' } Preview x = { a: 2, b: "o" }

- If we use subtle borders as signifiers of the equals sign in `x { a: 2, b: "o" }` (instead of the readable `x = { a: 2, b: "o" }`), my understanding is that those borders should meet [this WCAG 2.1 criterion for non-text contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) and reach a 3:1 contrast. Currently the two mockups seem far from that. On a white background, a passing value could be `#909090`:

[![Screenshot of contrast ratio test for #909090 on white, passing WCAG AA for large text and graphical elements](https://user-images.githubusercontent.com/243601/62193865-f63ab200-b378-11e9-9bd1-d63bd403a7ca.png)](https://webaim.org/resources/contrastchecker/?fcolor=909090&bcolor=FFFFFF)

**Comment by digitarald** [comment]
Thanks @fvsch for the a11y focused feedback; we should ensure that we keep those in mind when moving on to more detailed mockups.

> How should it read in a screen reader? 

Given that variables are also shown in the Scopes pane, I would lean on hiding the information from screen readers. A11y in Debugger's codemirror parts is in general a big question mark for me and something we should understand better.

> … those borders should meet this WCAG 2.1 criterion for non-text contrast and reach a 3:1 contrast

👍. I would add that the boxes need to have good contrast no matter what, as they otherwise blend in with the code and can't be told apart.

@violasong what are your initial thoughts?

**Comment by darkwing** [comment]
I really like the subtle boxes approach, and agree we should hide from screen readers.  I think the right-click interactions would be a great bunch of follow up items too!

**Comment by violasong** [comment]
I really like what I'm seeing here and in the debugger channel!

A few questions:

Do we expect folks to easily understand what this is? Most other editors use an equals sign/colon — would that help understanding?

<img width="203" alt="image" src="https://user-images.githubusercontent.com/55994/62419882-0e435780-b63f-11e9-9c3d-f5e82264fefc.png">

How important is the yellow? I usually like to keep it for warnings, but I see that yellow is common in a lot of editors. (And it looks like warnings/errors in quite a few of them!) Some editors (e.g. Jetbrains, below) make it look like a code comment. This feels intuitive to me, though it doesn't communicate interactivity.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/55994/62419658-75124200-b63a-11e9-8cf5-5f92bb5f048a.png">

It does help if we tone down the yellow a bit.

<img width="237" alt="image" src="https://user-images.githubusercontent.com/55994/62419895-40ed5000-b63f-11e9-80e1-9b68c25fb8be.png">

A colon could be added:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/55994/62419897-52365c80-b63f-11e9-9925-260a2a9d8650.png">

A few other tests:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/55994/62419905-9aee1580-b63f-11e9-809d-252135c3d51b.png">

[Figma source](https://www.figma.com/file/dgxFlapWDxfbGkZm8CKB6C/Untitled?node-id=0%3A1) :)

**Comment by dhyey35** [comment]
@violasong I think people would be easily able to understand which one is variable name and which is it's value, so an `=` would just use extra space every time.

**Comment by fvsch** [comment]
> A few other tests:
> 
> <img alt="image" width="258" src="https://user-images.githubusercontent.com/55994/62419905-9aee1580-b63f-11e9-809d-252135c3d51b.png">

These and the toned-down yellow ones are all pretty good. I like the purple one and first gray one, for no particular reason.

I still think having a symbol between the expression and value helps, and the colon or arrow might be less ambiguous than the equals sign (which could be understood as an assignment operator).

**Comment by digitarald** [comment]
> A colon could be added:

@violasong one reason for the design change was that we could make the variable name clickable to collapse the variable. Some can be massive space hogs and collapsing them reduces clutter and can even help to clean the output up for taking a screenshot.

> How important is the yellow?

We assume Chrome users are trained on it, and as you saw it seems to be the go to in many editors. Purple, which I am a fan of, might work just as well – and so does gray as it makes the syntax highlighting that preview uses a bit more vibrant.

Beyond a single color: Another idea discussed, which we can talk about when we get there, is to differentiate changed variables by color. A yellow highlight could be applied to updates.

In the backlog we also have inline preview for errors (which Chrome supports nicely, and which makes clicking from console errors to the source a lot more affordable), but also preview for console logs; bringing more context from the console into the source. Those would also be great elements to color code.

> first gray one, for no particular reason.

**Comment by digitarald** [comment]
@violasong one aspect you might have seen in the shared screenshots, would be to mock up when previews on 2 lines, touching bottom to top, look like.

![image](https://user-images.githubusercontent.com/8599/62439715-b28dd280-b701-11e9-9dfb-64f6c8473909.png)

With line-height in mind, maybe borders could blend into a single line, or we try to keep some whitespace.

**Comment by violasong** [comment]
> I still think having a symbol between the expression and value helps, and the colon or arrow might be less ambiguous than the equals sign (which could be understood as an assignment operator).

Yeah, I had this thought as well about the equals. I like that arrow means "output," but I'm guessing the colon will be the most commonly understood.

> I think people would be easily able to understand which one is variable name and which is it's value, so an `=` would just use extra space every time.

I guess I'm thinking of situations of unfamiliar code, where variable names might not be obvious - and just a colon wouldn't take much space.

> one reason for the design change was that we could make the variable name clickable to collapse the variable. Some can be massive space hogs and collapsing them reduces clutter and can even help to clean the output up for taking a screenshot.

Design change: As in the subtle boxes? 
- Interesting. I think we'd need a bit more indication for clickability then. 
- Should we truncate long previews, or do we want to show the full output by default?
- I feel I'd want the whole thing to be clickable to expand, like Console groups. If we still use the subtle-boxes look, it would be decorative.

Example with "Console style" - truncated, disclosure arrow, fully clickable:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/55994/62500298-a99d0f80-b79a-11e9-8148-fb6c9823fa52.png">

With subtle boxing, for an extra sense of being a button/badge:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/55994/62500347-d3563680-b79a-11e9-8a33-a8d6d6b951d3.png">

**Comment by violasong** [comment]
> > How important is the yellow?
> 
> We assume Chrome users are trained on it, and as you saw it seems to be the go to in many editors. Purple, which I am a fan of, might work just as well – and so does gray as it makes the syntax highlighting that preview uses a bit more vibrant.

I'd actually describe Chrome's color as Peach Yogurt :D

...and it reads as midway between warning and error to me, especially when the previews are super long like in your screenshots.

>In the backlog we also have inline preview for errors (which Chrome supports nicely, and which makes clicking from console errors to the source a lot more affordable), but also preview for console logs; bringing more context from the console into the source. Those would also be great elements to color code.

Sounds like now would be a good time to determine colors for all these situations. Preview for console logs might need to claim purple, since log points use purple.

**Comment by digitarald** [comment]
> Should we truncate long previews, or do we want to show the full output by default?

Maybe @dhyey35 has thoughts on truncation; as we will hit reps bottlenecks with massive objects. We can leave this off the table until we know what we can do within reps.

> Interesting. I think we'd need a bit more indication for clickability then.
> …
> I feel I'd want the whole thing to be clickable to expand, like Console XHR messages. If we still use the subtle-boxes look, it would be decorative.
> …
> truncated, disclosure arrow, fully clickable:

The arrow seems to borrow from trees and vertically expandable elements; which isn't the case here. Space is a premium in this case, so I would want to see if users get it without an icon. The feature would be also ok to be found through exploration.

The preview would not expand vertically; but could maybe use the preview tooltip or jump to the expanded object in the Scopes panel. Overall Debugger has existing UI for this that works really well for expanding objects.

> Example with "Console style"

The boxes seem to have grown compared to the prior iterations. Maybe it makes sense to mock them up in context of code, to see how well they visually separate from code and align when they are close to each other?

> Sounds like now would be a good time to determine colors for all these situations. Preview for console logs might need to claim purple, since log points use purple.

Not sure if users already have that association. Since logs can happen a lot throughout instrumented code, making them more subtle might also be worth an exploration.

**Comment by violasong** [comment]
> The arrow seems to borrow from trees and vertically expandable elements; which isn't the case here. Space is a premium in this case, so I would want to see if users get it without an icon. The feature would be also ok to be found through exploration.
> 
> The preview would not expand vertically; but could maybe use the preview tooltip or jump to the expanded object in the Scopes panel. Overall Debugger has existing UI for this that works really well for expanding objects.

Ah, I see what you mean. It's more like an Inspector badge then. Making the whole area clickable area still seems best to me. 

<img width="349" alt="image" src="https://user-images.githubusercontent.com/55994/62580395-f0523e80-b85a-11e9-954c-3c3fc86ebda1.png">

>The boxes seem to have grown compared to the prior iterations. Maybe it makes sense to mock them up in context of code, to see how well they visually separate from code and align when they are close to each other?

I was about to say they haven't changed but they did accidentally get 1px taller somehow 😅  ([here they are together](https://www.figma.com/file/dgxFlapWDxfbGkZm8CKB6C/Untitled?node-id=0%3A1)) - but yes, this is a good next step to mock up :)

**Comment by violasong** [comment]
Here's how this could look:
(changed font size to a step smaller than the code, and height of badge to match line height (15px))

<img width="832" alt="image" src="https://user-images.githubusercontent.com/55994/62581514-5391a000-b85e-11e9-8b12-061ffc088975.png">

**Comment by violasong** [comment]
Thought through the colors more and I'm still liking the purple. 

Re: the other colors: 
- Blue: Primary color, used in the most places and representing breakpoints, focus, and on-states. Could also be used for active line highlight in the future (if we want to match style editor on this) and general UI like toggled-on badges. Best to avoid for special UI like this.
- Yellow: For warning messages. Currently used as a hover-highlight color (which should probably be blue instead) and flash effects.
- Red: Error messages
- Grey: The Inspector badge off-state color. In Debugger, sounds like we could use it for understated messages such as logging.
- Green: Success color, and used in diffs for added lines. I [tried it out](https://www.figma.com/file/dgxFlapWDxfbGkZm8CKB6C/Untitled?node-id=21%3A14) in context but it sticks out a bit too much in this color scheme.

Here's purple + boxed effect

<img width="746" alt="image" src="https://user-images.githubusercontent.com/55994/62584881-3e6f3e00-b86b-11e9-8c8c-f92f85da180f.png">

**Comment by digitarald** [comment]
> changed font size to a step smaller than the code

Figma says 10px, is that correct? I have not found other obvious places where DevTools uses 10px. Trying to avoid scaling down the UI too much, how would this work with 11px?

> Here's purple + boxed effect

With border find this somehow better to comprehend. Maybe because purple is also used in some parts of the syntax highlighting, it doesn't set itself apart as much as it should?

It also separates the boxes better for multiple variables, which tend to blend together more in the other screenshot.

The other side effect is that the lighter preview area helps with color contrast.

<section>
Aside for yellow …
<details>

> Yellow: For warning messages. Currently used as a hover-highlight color (which should probably be blue instead) and flash effects.

For the long term, I like to better understand this, so it can inform future use of yellow: Do we have frequent warnings across panels that this might compete with? Yellow element highlighting is a "standard" UX across the web to focus attention; even in non-warning cases.
</details</section>

**Comment by violasong** [comment]
>Figma says 10px, is that correct? I have not found other obvious places where DevTools uses 10px. Trying to avoid scaling down the UI too much, how would this work with 11px?

Here's how it looks with 11px:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/55994/62666152-09c8b880-b937-11e9-8ca1-3401d19ff69a.png">

I think the smaller font size fits into the badges better. The Inspector's badge font is even smaller - 9px.

**Comment by digitarald** [comment]
Yesterday I thought 10px works definitely better, but today I like both again – while 10px gives it a bit more room to breath.

[Here](https://www.figma.com/file/C5EaKbRMiSNObONM2jcwf3/Inline-Preview-Fork?node-id=0%3A1) is a take with reduced box size, hairline borders and 11px:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/8599/62808514-1ec75800-baad-11e9-9816-27d224f9d4b3.png">

@violasong since we are down to pixel-tweaking, would it make sense to pick one fav now and then keep filing follow up fixes after reviewing the landed design?

**Comment by violasong** [comment]
Ah, interesting idea! Looking at these side-by-side though, I still think 10px is the easiest to comprehend due to the extra contrast in look/padding. It seems easier to jump my eye between the code and the previews.

Sounds good to follow up on tweaking later - would be great to see this in more real world contexts.

**Comment by digitarald** [comment]
OK, your latest 10px version is the final light design then, posted https://github.com/firefox-devtools/ux/issues/86#issuecomment-518886258

@jasonLaster brought up that we also need a dark mode version; after that we can probably close out this bug and file new ones for follow up tweaks.

**Comment by violasong** [comment]
Here's the [dark mode version](https://www.figma.com/file/dgxFlapWDxfbGkZm8CKB6C/Debugger-Inline-Variables?node-id=53%3A10) which uses colors based on the dark syntax purple.

**Comment by fvsch** [comment]
Tip: one way to simulate a 1x screen (if you don't have one) is to open the Browser Toolbox and run `:screenshot --dpr 1`, then open the resulting image in your image viewer or editor of choice.

**Comment by violasong** [comment]
Thanks all for the work on this. Sounds like this issue can be closed?

**Comment by digitarald** [comment]
Yes, this feature turned out great; looking forward to user feedback!
