### ISSUE TITLE
Enable logging event breakpoints

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/ux#92]
We currently have "Event Listener Breakpoints", "DOM Mutation Breakpoints", and "XHR Breakpoints". We'll soon have "Watchpoints". All of these features enable pausing at some point in time. It would be great if we could also enable logging at these points in time.

The benefit is that sometimes you do not want to pause at ONE point, but instead log all of the points and view the sequence of events...

It would also be helpful to be able to conditionally log/pause at these events to prevent some of the noise.

I think there are three levels of logging we can enable:

1. toggle logging for all types of event breakpoints
2. toggle logging for a type of event breakpoints e.g. xhr breakpoints
3. toggle logging for a specific breakpoint

### Option 1

it would likely be somewhere global like next to the disable breakpoints button.

### Option 2

![panel](https://user-images.githubusercontent.com/254562/64805115-28792b00-d545-11e9-928a-f8697760fdba.png)

### Option 3

![bp](https://user-images.githubusercontent.com/254562/64805123-2ca54880-d545-11e9-873c-e74260ea03dd.png)

Here is a [figma](https://www.figma.com/file/QQRYFSOjsfTffnwvcTdKGn/Event-Breakpoints?node-id=1%3A22) where we can sketch

---

One other thing to discuss is how to show the logged events in the console. The most similar example is log points where we show a purple breakpoint.

Here is a loom [video](https://www.loom.com/share/b3aa52604828421bb1487812bce493f8) of me using the feature.

**Comment by fvsch** [comment]
I like Option 3 because it's the most powerful and a good first step for starting to treat breakpoints as "points in time" when users can choose to (conditionally) log and/or break. As a power user this feels like the least hassle for getting the most control.

But I'm unclear on what the main use cases are and I'm wondering if Option 2 wouldn't serve them better. If the main use case is about logging a lot of events as they happen to get a wide view of "what is happening when I do X", a category-wide toggle might be better than tweaking every kind of Event breakpoint family or single breakpoint to turn them into log points (that would be a lot of manual work)?

**Comment by fvsch** [comment]
> treat breakpoints as "points in time" when users can choose to (conditionally) log and/or break

Illustration with two variants on the "Option 3 > on select" UI:

![Screen Shot 2019-09-13 at 18 27 24](https://user-images.githubusercontent.com/243601/64878648-471a1780-d654-11e9-90fb-d6fef9a16f01.png)

**Comment by jasonLaster** [comment]
>  If the main use case is about logging a lot of events

That's a good point. I'm not sure if users will want to log some events and pause on others.

**Comment by digitarald** [comment]
> That's a good point. I'm not sure if users will want to log some events and pause on others.

Right. Question would be if we map `monitorEvent` to UI, it does add levels of complication. Toggling a whole panel from pausing to logging does not map to how Logpoints work atm.

The settings dialog is similar to what I had put together as "overkill"-option for logpoints: https://www.figma.com/file/j42gN7Kjko8NcJfb6aVDIQ/Logpoints?node-id=0%3A1

**Comment by digitarald** [comment]
Now in Nightly, design by Jason:

![image](https://user-images.githubusercontent.com/8599/65192775-30493b80-da2d-11e9-8899-910671751471.png)

**Comment by violasong** [comment]
This looks great - nice work Jason!

Does this solve the problem for now, or are we still considering finer-grained logging options?

**Comment by digitarald** [comment]
Works for now! Next phase is gathering some feedback.

**Comment by digitarald** [comment]
Only general follow up would be to maybe come up with something better than checkbox/label design for those panel options. We used the same for Map Scopes and it does feel sub-optimal (while exposing it nicely), so worth a discussion.

**Comment by digitarald** [comment]
Landed and solved for now until we have better ideas.
