### ISSUE TITLE
Improve visibility of checked state in console/network toolbar

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/ux#95]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1582703

**Comment by violasong** [comment]
Closing this bug as progress has been made and moved into [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1590432) :)

<img width="907" alt="image" src="https://user-images.githubusercontent.com/55994/67530755-fb0bbb00-f674-11e9-918e-9cdc1d835380.png">
