### ISSUE TITLE
Consistent search highlight UI

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/ux#96]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1582702

Recent history was that Network search adopted Debugger's bolder highlighting and that I filed a bug to reduce padding as it looked off in the small space: https://bugzilla.mozilla.org/show_bug.cgi?id=1580030

Affects
- Debugger file search
- Inspector rules search
- Network full text search
- (Probably other placed I missed)

**Comment by lloan** [comment]
@digitarald 

If we change the highlight color in the network panel, will the debugger panel, for example, have to update their highlight color for search too? To keep it all consistent?

**Comment by fvsch** [comment]
I think #14 has a similar scope.

**Comment by digitarald** [comment]
Oh yes thank you! #14 seems to be a lot further in and with more scope. Duping this and continuing there.
