### ISSUE TITLE
Performance analysis not working in Firefox 70

### ISSUE THREAD

**Issue by lamka02sk** [firefox-devtools/ux#97]
The performance analysis tool stopped working after update to Firefox 70. Sometimes, it is just displayed for a few milliseconds and then only empty graphs. I am running Ubuntu 18.04 and Firefox is installed from apt repositories.

![Screenshot_20191025_110536](https://user-images.githubusercontent.com/8135372/67558717-c866ce80-f717-11e9-9bb2-3872f31aab85.png)

**Comment by violasong** [comment]
Thanks for filing this! This bug will be handled on bugzilla at this link: https://bugzilla.mozilla.org/show_bug.cgi?id=1589578

**Comment by violasong** [comment]
(Or actually, this particular bug seems to be fixed. Let us know if you notice any other issues.)
